# Generated by Django 4.2.5 on 2023-09-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ws_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
    ]
