# Generated by Django 4.2.5 on 2023-09-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_app', '0002_alter_message_options_remove_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
